name = "MassSpecBioChemicals"
uuid = "f4388e49-ae39-433b-b921-aa66233e9152"
authors = ["Yu-Fong Peng <sciphypar@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MassSpecChemicals = "a0caa3fb-cd40-4122-b5cb-396daad418a9"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ZipArchives = "49080126-0e18-4c2a-b176-c102e4b3760c"

[compat]
Dates = "1.10, 1.11"
Downloads = "1"
IterTools = "1.10"
MLStyle = "0.4"
MassSpecChemicals = "0.2, 0.3"
Reexport = "1"
ZipArchives = "2"
julia = "1.10, 1.11, 1.12"
